use_frameworks!

platform :ios, '9.0'

target 'LKMapSDK_Base_Example' do
#  pod 'LKMapSDK_Base', :path => '../'
pod 'LKMapSDK_Base', '~> 2.4.0'

  target 'LKMapSDK_Base_Tests' do
    inherit! :search_paths

    
  end
end
